config/routes.rb
Rails.application.routes.draw do
  get '/dilemmas/overdue', to: 'dilemmas#overdue', as: 'overdue'
  # resources :factors, only: [:destroy, :new, :create]
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :dilemmas
  resources :tags
  resources :comments
  # resources :users
  # resources :options
  root to: 'welcome#home'

  resources :dilemmas, only: [:show] do
    resources :options do
      resources :factors, only: [:destroy, :new, :create]
    end
  end
end

app/models/option.rb
class Option < ApplicationRecord
  validates :name, presence: {name: "option name must not be blank"}
  belongs_to :dilemma
  has_many :factors
  before_destroy :destroy_factors

  def factors_attributes=(factor_hash)
    factor_hash.each do |num_key, hash|
      if hash[:name] != "" && hash[:points] != ""
        if self.factors.include?(Factor.find_by(id: hash[:id]))
          factor = Factor.find_by(id: hash[:id])
          factor.update(name: hash[:name], points: hash[:points])
          factor.save
        else
          new_fact = Factor.create(hash)
          self.factors << new_fact
          self.save
        end
      end
    end
  end

  def total_points
    sum = 0
    self.factors.each do |f|
      sum += f.points
    end
    sum
  end

  def destroy_factors
    self.factors.each do |f|
      f.destroy
    end
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :require_login, only: [:new, :edit, :show]
  def new
    @option = Option.new
  end

  def create
    @option = current_user.current_dilemma.options.create(option_params)
    validate_option_and_factors
  end

  def edit
    set_option
  end

  def update
    set_option
    @option.update(option_params)
    validate_option_and_factors
  end

  def show
    set_option
  end

  def destroy
    set_option
    @option.destroy
    redirect_to dilemma_path(current_user.current_dilemma)
  end

  private
  def option_params
    params.require(:option).permit(:name, factors_attributes: [:name, :points, :id])
  end

  def set_option
    @option = Option.find_by(id: params[:id])
  end

  def validate_option_and_factors
    if @option.invalid? && @option.name != ""
      @option.factors.each do |fact|
        if fact.invalid?
          binding.pry
          @option.factors.delete(fact)
          flash[:message] = fact.errors.messages[:points].first
        else
          fact.option_id = @option.id
          fact.save
        end
      end
      @option.save
      redirect_to edit_dilemma_option_path(@option.dilemma, @option)
    elsif @option.name == ""
      flash[:message] = @option.errors.details[:name].first[:name]
      @option.id ? (redirect_to edit_dilemma_option_path(@option.dilemma, @option)) : (redirect_to new_dilemma_option_path)
    else
      redirect_to dilemma_option_path(@option.dilemma, @option)
    end
  end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_new_and_edit_options.html.erb
<%= render 'layouts/dilemma_header', {dilemma: current_user.current_dilemma} %>
<p>tags: <%= render 'layouts/dilemma_tags', {dilemma: current_user.current_dilemma} %></p>

<%= form_for [current_user.current_dilemma, option] do |o| %>
  <%= o.label :name %>
  <%= o.text_field :name %><br>
  <br>
  <%= o.label :factors %><br>
  <% if option.id == nil %>
    <% 5.times do %>
      <%= o.fields_for :factors, Factor.new do |fact| %>
        <%= fact.label :name %>
        <%= fact.text_field :name %>
        <%= fact.label :points %>
        <%= fact.text_field :points %>
      <% end %><br>
    <% end %>
  <% else %>
    <%= o.fields_for :factors, option.factors do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :points %>
      <%= f.text_field :points %><br>
    <% end %><br>
  <% end %>
  <%= o.submit %>
<% end %>

app/views/options/edit.html.erb
<%= render 'options/new_and_edit_options', {option: @option} %>

app/views/options/new.html.erb
<%= render 'options/new_and_edit_options', {option: @option} %>

app/views/options/show.html.erb
<%= render 'layouts/dilemma_header', {dilemma: @option.dilemma} %>
<p>tags: <%= render 'layouts/dilemma_tags', {dilemma: @option.dilemma} %></p>

<h4><%= @option.name %></h4>

<table>
  <tr>
    <th>factors</th>
    <th>points</th>
  </tr>
  <% @option.factors.each do |fact| %>
    <tr>
      <td><%= fact.name %></td>
      <td><%= fact.points %></td>
      <% if author_check(@option.dilemma.author) %>
        <td><%= link_to "delete", dilemma_option_factor_path(current_user.current_dilemma, @option, fact), method: "delete" %></td>
      <% end %>
    </tr>
  <% end %>
  <tr>
    <th>total</th>
    <th><%= @option.total_points %></th>
  </tr>
</table><br>

<% if author_check(@option.dilemma.author) %>
  <%= link_to "new factor", new_dilemma_option_factor_path(current_user.current_dilemma, @option, option_id: @option.id) %><br>
  <%= link_to "edit", edit_dilemma_option_path(current_user.current_dilemma, @option) %> | <%= link_to "delete this option", dilemma_option_path(@option), method: "delete" %>
<% end %>