config/routes.rb
Rails.application.routes.draw do
  get '/dilemmas/overdue', to: 'dilemmas#overdue', as: 'overdue'
  # resources :factors, only: [:destroy, :new, :create]
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :dilemmas
  resources :tags
  resources :comments
  # resources :users
  # resources :options
  root to: 'welcome#home'

  resources :dilemmas, only: [:show] do
    resources :options do
      resources :factors, only: [:destroy, :new, :create]
    end
  end
end

app/models/dilemma.rb
class Dilemma < ApplicationRecord
  validates :name, presence: {name: "dilemma name must not be blank"}
  validates :deadline, presence: true

  has_many :comments
  has_many :commenters, class_name: "User", through: :comments
  belongs_to :author, class_name: "User"
  has_many :options
  has_many :factors, through: :options
  has_many :dilemma_tags
  has_many :tags, through: :dilemma_tags

  before_destroy :destroy_options

  def tags_attributes=(tag_hash)
    tag_hash.each do |num_key, hash|
      if hash[:name] != ""
        tag = Tag.create(hash)
        self.tags << tag
        self.save
      end
    end
  end

  def best_option
    has_most_points = nil
    self.options.each do |opt|
      if has_most_points == nil
        has_most_points = opt
      elsif opt.total_points > has_most_points.total_points
        has_most_points = opt
      end 
    end
    has_most_points.name
  end

  def overdue?
    self.deadline < Time.now ? true : false
  end

  def pretty_deadline
    self.deadline.strftime("%A, %d %b %Y")
  end

  def destroy_options
    self.options.each do |o|
      o.destroy
    end
  end

end

app/controllers/dilemmas_controller.rb
class DilemmasController < ApplicationController
  before_action :require_login, only: [:new, :edit, :show, :index, :overdue]

  def new
    @dilemma = Dilemma.new
  end

  def create
    @dilemma = current_user.dilemmas.create(dilemma_params)
    validate_dilemma
  end

  def edit
    @dilemma = current_user.current_dilemma
  end

  def update
    set_dilemma
    @dilemma.update(dilemma_params)
    validate_dilemma
  end

  def show
    set_dilemma
    if @dilemma.author == current_user
      current_user.current_dilemma = current_user.dilemmas.find_by(id: params[:id])
    end
    respond_to do |format|
      format.html {render :show}
      # format.json {render json: @dilemma.to_json(include: [:tags, comments: {include: :commenter}, options: {include: :factors}])}
      format.json {render json: @dilemma}
    end
  end

  def index
    @dilemmas = current_user.dilemmas
    respond_to do |format|
      # format.json {render json: @dilemmas.to_json(include: [:tags, :comments, options: {include: :factors}])}
      format.json {render json: @dilemmas}
      format.html {render :index}
    end
  end

  def destroy
    set_dilemma
    @dilemma.destroy
    redirect_to dilemmas_path
  end

  def overdue
  end

  private
  def dilemma_params
    params.require(:dilemma).permit(:name, "deadline(3i)", "deadline(2i)", "deadline(1i)", tags_attributes: [:name], tag_ids: [])
  end

  def set_dilemma
    @dilemma = Dilemma.find_by(id: params[:id])
  end

  def validate_dilemma
    if @dilemma.invalid?
      flash[:message] = @dilemma.errors.details[:name].first[:name]
      if @dilemma.id
        redirect_to edit_dilemma_path(@dilemma)
      else
        redirect_to new_dilemma_path
      end
    else
      current_user.current_dilemma = @dilemma.id
      redirect_to dilemma_path(@dilemma)
    end
  end
end

app/helpers/dilemmas_helper.rb
module DilemmasHelper
  def dilemma_link(dilemma)
    link_to(dilemma.name, dilemma_path(dilemma))
  end

  def author_deadline(dilemma)
    "author: #{dilemma.author.email} | deadline: #{dilemma.pretty_deadline}"
  end

end

app/views/dilemmas/_form.html.erb
<%= form_for dilemma do |d| %>
  <%= d.label :name %>
  <%= d.text_field :name %><br>
  <%= d.label :deadline %>
  <%= d.date_select :deadline, order: [:day, :month, :year] %><br>
  <%= d.label "existing tags:" %>
  <%= d.collection_check_boxes :tag_ids, Tag.all, :id, :name %><br>
  <%= d.label "add new tag: " %>
  <%= d.fields_for :tags, dilemma.tags.new do |t| %>
    <%= t.label :name %>
    <%= t.text_field :name%>
  <% end %><br>
  <%= d.submit %>
<% end %>

app/views/dilemmas/edit.html.erb
<%= render 'dilemmas/form', {dilemma: @dilemma} %>

app/views/dilemmas/index.html.erb
 <table>
  <tr id="dilemma_index_header_row" data-current-user-id="<%= current_user.id %>">
    <th>dilemma</th>
    <th>deadline</th>
    <th>tags</th>
  </tr>
  <!-- dilemmas added here via jquery -->
  <tr>
    <td><%= link_to "add new dilemma", new_dilemma_path %></td>
    <td><%= link_to "see your overdue dilemmas", overdue_path %></td>
    <td><%= link_to "see all tags", tags_path %></td>
  </tr>
</table>

<script type="text/javascript">
  getDilemmas();
</script>

<script type="text/x-handlebars-template" id="dilemma-index-template">
  <tr>
    <td><a href="/dilemmas/{{dilemma_id}}">{{dilemma_name}}</a></td>
    <td>{{dilemma_deadline}}</td>
    <td>
      {{#each tags}}
        <a href="/tags/{{tag_id}}">{{tag_name}}</a>
      {{/each}}
    </td>
    <td>
      <a rel='nofollow' data-method='delete' href='/dilemmas/{{dilemma_id}}'>delete</a>
    </td>
  </tr>
</script>

app/views/dilemmas/new.html.erb
<%= render 'dilemmas/form', {dilemma: @dilemma} %>

app/views/dilemmas/overdue.html.erb
<% if current_user.overdue_dilemmas.first %>
  <table>
    <tr>
      <th>dilemma</th>
      <th>deadline</th>
      <th>tags</th>
    </tr>
    <% current_user.overdue_dilemmas.each do |d| %>
      <%= render 'layouts/table', {d: d} %>
    <% end %>
  </table>
<% else %>
  <p>you don't have any overdue dilemmas, good job</p>
<% end %>

app/views/dilemmas/show.html.erb
<%= render 'layouts/dilemma_header', {dilemma: @dilemma} %>
<p>tags: <%= render 'layouts/dilemma_tags', {dilemma: @dilemma} %></p>

<table>
  <tr>
    <th>options</th>
    <th>total points</th>
  </tr>
  <% @dilemma.options.each do |opt| %>
    <tr>
      <td><%= "#{opt.name}"%></td>
      <td><%= "#{opt.total_points}" %></td>
      <td><%= link_to "view", dilemma_option_path(@dilemma, opt) %></td>
      <td><%= link_to "delete", dilemma_option_path(@dilemma, opt), method: "delete" if author_check(@dilemma.author) %></td>
    </tr>
  <% end %>
</table>

<% if author_check(@dilemma.author) %>
  <%= link_to "add new option", new_dilemma_option_path(@dilemma) %>
  <br>

  <%= link_to "edit", edit_dilemma_path(current_user.current_dilemma) %> | <%= link_to "delete this dilemma", dilemma_path(@dilemma), method: "delete" %>
<% end %>
<br>
<br>

<div id="comment_text"></div>

<div id="comment_table" data-dilemma-id="<%= @dilemma.id %>" data-author-id="<%= @dilemma.author.id %>" data-current-user-id="<%= current_user.id %>">
  <table>
    <tr id="comment_header_row">
      <th>user</th>
      <th>comment</th>
    </tr>
      <!-- js adds old comments here -->
      <!-- js adds new comments here -->

    <tr id="comment_create_row">
      <td></td>
      <td>
        <%= form_for @dilemma.comments.new do |com| %>
          <%= com.hidden_field :dilemma_id, value: @dilemma.id %>
          <%= com.hidden_field :commenter_id, value: current_user.id %>
          <%= text_area :comment, :content, value: "add a new comment" %><br>
          <input type="submit" name="commit" value="Create Comment" data-disable-with="Create Comment" id="new_comment">
        <% end %>
      </td>
    </tr>
  </table>
</div>  <!-- comment_table -->

<script type="text/javascript">
  getAndDisplayComments();
</script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.min.js"></script>

<script type="text/x-handlebars-template" id="comment-template">
  <tr>
    <td>{{email}}</td>
    <td>{{content}}</td>
    {{#if boolean}}
      <td><a rel='nofollow' data-method='delete' href="/comments/{{id}}">delete</a></td>
    {{/if}}
  </tr>
</script>