config/routes.rb
Rails.application.routes.draw do
  get '/dilemmas/overdue', to: 'dilemmas#overdue', as: 'overdue'
  # resources :factors, only: [:destroy, :new, :create]
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :dilemmas
  resources :tags
  resources :comments
  # resources :users
  # resources :options
  root to: 'welcome#home'

  resources :dilemmas, only: [:show] do
    resources :options do
      resources :factors, only: [:destroy, :new, :create]
    end
  end
end

app/views/layouts/_dilemma_header.html.erb
<h3><%= dilemma_link(dilemma) %></h3>
<h5><%= author_deadline(dilemma) %></h5>

app/views/layouts/_dilemma_tags.html.erb
<% dilemma.tags.collect do |t| %>
  <%= link_to t.name, tag_path(t) %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<ul style="text-align: center;">
  <% flash.each do |key, msg| %>
    <li style="color:red; list-style-type:none;"><%= msg if msg.class == String %></li>
  <% end %>
</ul>

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
  <%= "Welcome, #{current_user.email}" %><br>
  <%= link_to "home", dilemmas_path %> | 
  <%= link_to "sign out", destroy_session_path(current_user), method: "delete" %>
<% else %>
  <%= link_to "home", root_path %> | 
  <%= link_to "log in or sign up", new_user_registration_path %>
<% end %>
<br>

app/views/layouts/_table.html.erb
<tr>
  <td><%= link_to d.name, dilemma_path(d) %></td>
  <td><%= d.pretty_deadline %></td>
  <td>
    <% d.tags.each do |t| %>
      <%= link_to t.name, tag_path(t) %>
    <% end %>
  </td>
  <% if author_check(d.author) %>
    <td><%= link_to "view/edit", dilemma_path(d) %></td>
    <td><%= link_to "delete", dilemma_path(d), method: "delete" %></td>
  <% end %>
</tr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DilemmaApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <div class="nav">
      <h1>can't make up your mind?</h1>
      <%= render 'layouts/navigation' %><br>
    </div> <!-- nav -->

    <div id="center">
      <%= yield %><br>
    </div> <!-- center -->
    <div class="flash_messages">
      <%= render 'layouts/flash_messages' %>
    <footer>
      <p>by jd2rogers2 - copywrite 2016</p>
    </footer>
    </div> <!-- flash_messages -->
  </body>
</html>